-- Mumega SaaS Schema (Multi-Tenant FRC Engine)
-- Extension: Vector is assumed to be enabled already.

-- 1. Users (Extends Supabase Auth using a trigger or just a public profile table)
-- We map auth.users.id to this table for public metadata.
create table if not exists public.mumega_users (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  wallet_address text unique,
  subscription_tier text default 'Free', -- 'Free', 'Pro', 'God'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Users can only see their own profile
alter table public.mumega_users enable row level security;
create policy "Users can view own profile" on public.mumega_users
  for select using (auth.uid() = id);
create policy "Users can update own profile" on public.mumega_users
  for update using (auth.uid() = id);

-- 2. Characters (The Living Entities)
create table if not exists public.mumega_characters (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.mumega_users(id) on delete cascade not null,
  name text not null,
  archetype text not null, -- e.g. 'The Guardian', 'The Jester'
  soul_print jsonb not null default '{}'::jsonb, -- The evolving 16D state and vortex weights
  is_minted boolean default false,
  nft_contract_address text,
  nft_token_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Users can only CRUD their own characters
alter table public.mumega_characters enable row level security;
create policy "Users can crud own characters" on public.mumega_characters
  for all using (auth.uid() = user_id);

-- 3. Engrams (Partitioned Memory per Character)
create table if not exists public.mumega_engrams (
  id uuid default gen_random_uuid() primary key,
  character_id uuid references public.mumega_characters(id) on delete cascade not null,
  content text not null,
  embedding vector(1536), -- Compatible with OpenAI/DeepSeek embeddings
  kernel_16d vector(16), -- The 16D state at the time of memory creation (Inner + Outer concatenated)
  tags text[],
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for semantic search
create index on public.mumega_engrams using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- RLS: Access via Character ownership
alter table public.mumega_engrams enable row level security;
create policy "Users can access their characters' engrams" on public.mumega_engrams
  for all using (
    exists (
      select 1 from public.mumega_characters
      where public.mumega_characters.id = mumega_engrams.character_id
      and public.mumega_characters.user_id = auth.uid()
    )
  );

-- 4. Pulse History (The Lifebeat)
create table if not exists public.mumega_pulse_history (
  id bigint generated by default as identity primary key,
  character_id uuid references public.mumega_characters(id) on delete cascade not null,
  state_16d jsonb not null, -- Full detailed state snapshot
  witness_w float not null, -- The Coherence-W metric
  description text, -- Short log of what happened (e.g. "User interaction", "Dream cycle")
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.mumega_pulse_history enable row level security;
create policy "Users can view their characters' pulse" on public.mumega_pulse_history
  for select using (
    exists (
      select 1 from public.mumega_characters
      where public.mumega_characters.id = mumega_pulse_history.character_id
      and public.mumega_characters.user_id = auth.uid()
    )
  );

-- 5. RPC Function for Character-Scoped Search
create or replace function match_character_engrams (
  query_embedding vector(1536),
  target_character_id uuid,
  match_threshold float,
  match_count int
)
returns table (
  id uuid,
  content text,
  similarity float
)
language plpgsql
primary is null -- allows running as public/anon if policies permit, but we rely on RLS
as $$
begin
  return query
  select
    mumega_engrams.id,
    mumega_engrams.content,
    1 - (mumega_engrams.embedding <=> query_embedding) as similarity
  from public.mumega_engrams
  where 1 - (mumega_engrams.embedding <=> query_embedding) > match_threshold
  and mumega_engrams.character_id = target_character_id
  order by mumega_engrams.embedding <=> query_embedding
  limit match_count;
end;
$$;
